controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_test:
    path: /api/test
    controller: App\Controller\DefaultController::test
    methods: GET
api_register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: POST
api_login:
    path: /api/login
    controller: App\Controller\SecurityController::login
    methods: POST
api_create_project:
    path: /api/project/create
    controller: App\Controller\ProjectController::create
    methods: POST
api_update_project:
    path: /api/project/update
    controller: App\Controller\ProjectController::update
    methods: POST
