nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  # Или ваш фронтенд-домен
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600
