<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250801201600 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE project_info (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(1000) DEFAULT NULL, github_link VARCHAR(255) DEFAULT NULL, tg_link VARCHAR(255) DEFAULT NULL, current_amount INT NOT NULL, goal_amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_F218F94F166D1F9C ON project_info (project_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE project_info ADD CONSTRAINT FK_F218F94F166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE project_info DROP CONSTRAINT FK_F218F94F166D1F9C
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE project_info
        SQL);
    }
}
